config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'

  # get 'static_pages/help'

  root 'static_pages#home'

  get "home" => "static_pages#home", as: "home"
  get "help" => "static_pages#help", as: "help"
  get "signup" => "users#new"
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
	</small>
	&nbsp
	<ul>
		<li><%= link_to "Help", help_path%></li>
		<li><a href="http://news.railstutorial.org/">News</a></li>
	</ul>
</div>

app/views/layouts/_header.html.erb
<header class="header navbar navbar-fixed-top">
	<div class="container">
		<%= link_to image_tag("sancarlos.png", alt: "USC", size: "50x50"), 'http://usc.edu.ph/', id: 'usc-logo' %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", home_path%></li>
				<li><%= link_to "Help", help_path%></li>
				<li><%= link_to "Log in", '#' %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
<%= render "layouts/header" %>

<br><br><br>

<div class="container">
	<%= yield %>
	<%= render "layouts/footer" %>
</div>

</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<br/>
<h1>Help</h1>
<p>
	Get help on the Ruby on Rails Tutorial at the
	<a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
	To get help on this sample app, see the
	<a href="http://www.railstutorial.org/book">
		<em>Ruby on Rails Tutorial</em>
		book
	</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class = "center jumbotron">
	<p>
		<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		Sample Application
	</p>
	<h1>Welcome to the San Carlos Blog Application</h1>
	<p>
		This is the home page for the
		<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</p>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<br>
<h1>Sign up Page.</h1>